FROM python:3-alpine

COPY . /app

WORKDIR /app

RUN pip install flask

EXPOSE 5000

#1. run with flask env 
ENV FLASK_APP index
ENV FLASK_ENV development
ENV FLASK_RUN_PORT 5000
ENV FLASK_DEBUG True

#ENTRYPOINT ["python", "-m"]
#CMD ["flask", "run", "--host=0.0.0.0"]
#OR
CMD python -m flask run --host=0.0.0.0

#2. run with python module at file (preferred by me :D)
#CMD ["python", "index.py"]

# alias p-test1='docker build -t python/test/flask -f "Dockerfile-test" .; docker run -d --rm --name my-py-test1 -p 5001:5000 -v $(pwd):/app python/test/flask; docker logs -f my-py-test1;'

#FLASK_ENV=development flask run